@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "email": "email@email.com", 
  "name": "name",
  "password": "password"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "email@email.com", 
  "password": "password"
}

###

# @name create-questions
POST {{baseUrl}}/questions
Content-Type: application/json
# Authorization: Bearer {{authToken}}
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTZkNTcyNS0xYjM5LTQ0YjgtYjVkNS03N2FjNzJiMzg0MjUiLCJpYXQiOjE3MzM4MTkyMTB9.IWeft3WbliD5FhpV7YkKZyM6EEzEQqzCd75Odl2tSullim63CgBad65pa_a3R678KIgxDI6BNyRaOAm8IfN2I7dqN1_IEIUBG6uNbnsUvq79_WjNdn86u8c0sxZI6aCrDnEHRqH1rHu4zF9k7g2dqDJODjYerxMeUYauk3LoBSWlLYLQ_zrVZvuuQMcahPvwy1nk1cjdb3XnlEnLr-EObSmalSWGFIj2j3y1v8qnjBfUFJ0eE5BHkUW2Bz2V9NsYrBUbQlTi4gOWaI30ZefRvWOMhTqqRNFgGHmS8KmPOuIWViuwcUr4OW6zFblSbXef5w7EIy4IJQpC48liug0C9A

{
  "title": "title",
  "description": "description",
  "tags": ["tag1", "tag2"]
}